apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: watchlist
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: mongodb
    tier: mongodb
  clusterIP: None