apiVersion: v1
kind: Service
metadata:
  name: movies-marketplace
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer
  selector:
    app: movies-marketplace