apiVersion: v1
kind: Service
metadata:
  name: movies-store
  namespace: {{ .Values.namespace }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    {{- if .Values.deployment.https.ssl }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:{{ .Values.services.aws.region }}:{{ .Values.services.aws.account }}:certificate/{{ .Values.deployment.https.ssl }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    {{- end }}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
    {{- if .Values.deployment.https.ssl }}
    - name: https
      port: 443
      targetPort: 3000
    {{- end }}
  type: LoadBalancer
  selector:
    app: movies-store