apiVersion: apps/v1
kind: Deployment
metadata:
  name: loader
  namespace: watchlist
spec:
  selector:
    matchLabels:
      app: loader
  template:
    metadata: 
      labels: 
        app: loader
    spec:
      containers:
      - name: loader
        image: adriannavarro/loader:develop
        imagePullPolicy: Always
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: SQS_URL
          value: https://sqs.eu-west-1.amazonaws.com/646390474080/movies_to_parse
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: dockerhubcredentials


