apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketplace
  namespace: watchlist
spec:
  selector:
    matchLabels:
      app: marketplace
  template:
    metadata: 
      labels: 
        app: marketplace
    spec:
      containers:
      - name: marketplace
        image: adriannavarro/marketplace:develop
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: dockerhubcredentials