apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser
  namespace: watchlist
spec:
  selector:
    matchLabels:
      app: parser
  template:
    metadata: 
      labels: 
        app: parser
    spec:
      containers:
      - name: parser
        image: adriannavarro/parser:develop
        env:
        - name: AWS_REGION
          value: eu-west-1
        - name: SQS_URL
          value: https://sqs.eu-west-1.amazonaws.com/646390474080/movies_to_parse
        - name: MONGO_DATABASE
          valueFrom:
            secretKeyRef:
              name: mongodb-access
              key: database
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-access
              key: uri
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: dockerhubcredentials