apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
  namespace: watchlist
spec:
  selector:
    matchLabels:
      app: store
  template:
    metadata: 
      labels: 
        app: store
    spec:
      containers:
      - name: store
        image: adriannavarro/store:develop
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-access
              key: uri
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: dockerhubcredentials