apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: movies-marketplace
  name: movies-marketplace
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: movies-marketplace
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: movies-marketplace
    spec:
      containers:
      - image: ID.dkr.ecr.REGION.amazonaws.com/mlabouardy/movies-marketplace:develop
        imagePullPolicy: ""
        name: movies-marketplace
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
