name: Python CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python/playground

    steps:
    - uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          src:
            - 'python/**'

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      if: steps.filter.outcome.src == 'true'
      run: |
        make install

    - name: Lint with pylint
      if: steps.filter.outcome.src == 'true'
      run: |
        make lint

    - name: Test with pytest
      if: steps.filter.outcome.src == 'true'
      run: |
        make test

    - name: Format code with Python Black
      if: steps.filter.outcome.src == 'true'
      run: |
        make format