name: Python CI
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python/playground

    steps:
    - uses: actions/checkout@v2

    - uses: dorny/paths-filter@v2
      with:
        filters: |
          - filter: 'python/playground/**'
            regex: true

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        if [ "${{ steps.filter.outputs.match }}" = "true" ]; then
          make install
        else
          echo "No changes in the src/ directory. Skipping the specific command."
        fi

    # - name: Lint with pylint
    #   # if: steps.filter.outputs == 'true'
    #   run: |
    #     make lint

    # # - name: Test with pytest
    # #    if: steps.filter.outcome.outputs == 'true'
    # #   run: |
    # #     make test

    # - name: Format code with Python Black
    #    #if: steps.filter.outcome.outputs == 'true'
    #   run: |
    #     make format