name: Python CI

on:
  push:
    branches:
      - main  
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: python/playground

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Filter Paths
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            src:
              - 'python/playground/**'

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        if: ${{ steps.filter.outputs.match == 'true' }}  # Check if there are changes in the specified paths
        run: |
          make install

      - name: Lint with pylint
        if: ${{ steps.filter.outputs.match == 'true' }}  # Check if there are changes in the specified paths
        run: |
          make lint

      # Uncomment and adjust the following lines if you have tests
      # - name: Test with pytest
      #   if: ${{ steps.filter.outputs.match == 'true' }}
      #   run: |
      #     make test

      - name: Format code with Python Black
        if: ${{ steps.filter.outputs.match == 'true' }}  # Check if there are changes in the specified paths
        run: |
          make format
